Enemies projectiles
ryiuthere/MashUpGameJam2022 pull request #3
Opened 2022-10-15 19:12 UTC by KBerndt10

- Created Projectile & Enemy classes
- Player now automatically shoots towards mouse
- Slight adjustments to BaseEntity
- Turned off gravity
- Projectiles and characters are now on their own physics lairs, projectiles can't collide with other projectiles & characters can't collide with other characters
- Added some enemy prefabs
- Added some projectile prefabs
- Player con now die

2022-10-15 20:50 UTC, ryiuthere requested changes
Added a couple comments.

2022-10-15 20:50 UTC, ryiuthere commented on Assets/Scripts/BaseProjectile.cs
> +    [SerializeField]
What's the purpose of this being serialized? I'd imagine this should only ever be set in code, and if we want to view its contents in real time we can always use debug mode.

2022-10-15 20:50 UTC, ryiuthere commented on Assets/Scripts/Enemies/BaseEnemy.cs
> +        this.player = GameObject.Find("Player");
We may want to consider adding a game manager object that we can attach the player to and reference the game manager, so that we don't have to worry about player name changing or accidental duplicate names. We'll probably use that game manager for any global objects that need to be referenced in several places i.e. UI, game status, etc

2022-10-15 22:24 UTC, KBerndt10 commented on Assets/Scripts/BaseProjectile.cs
> +    [SerializeField]
I was originally testing with projectiles that started on the map, and forgot to clean that up

2022-10-15 22:24 UTC, KBerndt10 commented on Assets/Scripts/Enemies/BaseEnemy.cs
> +        this.player = GameObject.Find("Player");
Will look into it

2022-10-16 00:00 UTC, ryiuthere approved these changes

2022-10-16 00:01 UTC, merged